### ISSUE TITLE
support CDNs

### ISSUE THREAD

**Issue by chmontgomery** [dowjones/gulp-bundle-assets#11]
detect cdn urls and, if present, don't bundle anything but instead add it to the `bundle.results.json` as a scripts/style include from the given url

**Comment by timelf123** [comment]
Can you give an example of how this would work?

I originally misread the title as being able to push your built files to a CDN. For those looking to do that, here is an easy way to do it with `gulp-cloudfront` and `gulp-awspublish`.

```
var gulp = require('gulp');
var cloudfront = require('gulp-cloudfront');
var awspublish = require('gulp-awspublish');

// AWS config object
var aws = {
  'params': {
    'Bucket': 'bucketname' // s3 bucket
  },
  'accessKeyId': 'yourAccessKeyId',
  'secretAccessKey': 'yourSecretAccessKey',
  'distributionId': 'yourCloudFrontDistributionId' 
};

var publisher = awspublish.create(aws);
var headers = {'Cache-Control': 'max-age=315360000, no-transform, public'};

/**
 * ITS CDN TIME
 */
gulp.task('cdn', function () {
    gulp.src('public/distribution/**')
        .pipe(awspublish.gzip())
        .pipe(publisher.publish(headers))
        .pipe(publisher.cache())
        .pipe(awspublish.reporter())
        .pipe(cloudfront(aws));
});
```

**Comment by chmontgomery** [comment]
@timelf123 right, this issue is not about pushing built files to a CDN. There are plenty of other good plugins already for that.

This is meant for the `bundle.result.json` file, i.e. the generated result could look like this:

```js
{
  "main": {
    "scripts": "<script src='//abc.akamai.net/main.js' type='text/jsx'></script>",
    "styles": "<link href='//abc.akamai.net/main.css' media='all' rel='stylesheet' type='text/css'/>"
  },
  "vendor": {
    "scripts": "<script src='//abc.akamai.net/vendor.js' type='text/javascript'></script>"
  }
}
```

Since this issue was written we added support for the [bundle.result `pathPrefex` option](docs/API.md#optionspathprefix). If that doesn't support your use case, we have a different issue open for a `pathPrefix` per bundle: https://github.com/dowjones/gulp-bundle-assets/issues/60
