### ISSUE TITLE
Allow skipping revision hash addition

### ISSUE THREAD

**Issue by chadwilken** [dowjones/gulp-bundle-assets#57]
I current have another tool setup to allow me to version my assets and need to use that. It doesn't work well with the revision hash added to the asset name. Is there a way to use this without getting the hash?

**Comment by chmontgomery** [comment]
Yes! All you need to do is use the `rev: false` option, e.g.

```js
bundle: {
  header: {
    scripts: [
      './js/header-scripts.js'
    ],
    styles: [
      './styles/header.css'
    ],
    options: {
      rev: false // {(boolean|string|Array)}
    }
  }
}
```

[See here for the option in action](https://github.com/dowjones/gulp-bundle-assets/blob/master/examples/full/bundle.config.js). If that doesn't work, let me know.

**Comment by chadwilken** [comment]
That is what I have but it doesnt seem to be working unless it is caching my config file or something

**Comment by chmontgomery** [comment]
Your config file will only be cached when in watch mode. Otherwise, every new invocation of `bundle()` should re-require your bundle config.

As is, your code looks fine. Do you have a project you can share with more context? Perhaps your full `bundle.config.js` and `gulpfile.js`?

**Comment by chadwilken** [comment]
Man sorry for the confusion something went haywire with my system and it was fine once I closed out of Visual Studio...Sorry too waste your time, thanks for the quick replies!

**Comment by chmontgomery** [comment]
np
