### ISSUE TITLE
Predictable and uniform hash ids for static assets

### ISSUE THREAD

**Issue by waynebloss** [dowjones/gulp-bundle-assets#67]
I would like to use your bundler in my gulpfile, but I see that you're using [gulp-rev](https://github.com/sindresorhus/gulp-rev) and I'm not sure how to get predictable and uniform hashes for my static assets with it. Let me explain what I mean by that.

Right now when you generate bundles they might come out like this:
```
   `main-8e6d79da08.css
   `main-5f17cd21a6.js
   `vendor-d66b96f539.js
```

But I would like them to come out like this, so that I know which files belong with the same build when they're deployed side by side with other deployments.
```
   `main-8e6d79da08.css
   `main-8e6d79da08.js
   `vendor-8e6d79da08.js
```

Also, I would like the hash value `8e6d79da08` to be generated in a predictable way, so that the bundling does not have to occur before I build the html. Lastly, I'd also like to be able to use that same hash value as a directory name instead of appending it to the filenames, if possible. This can be very useful for static sites and for versioning a web app within a larger static site.

With that in mind, here is what I do in my own build tool right now:

- Grab the package version of the project that's being built.
- Convert the version string to an integer by splitting on `.`, padding each section with zeroes, concatenating and then parsing to int.
- Feed it to [hashids](https://github.com/ivanakimov/hashids.node.js), which generates a deterministic hash for the integer (unless the configured salt or alphabet changes).

I want to keep this behavior, but I'm not sure where to integrate it into [gulp-bundle-assets](https://github.com/dowjones/gulp-bundle-assets). The [custom-result](https://github.com/dowjones/gulp-bundle-assets/tree/master/examples/custom-result) example looks promising but I'm not sure if you can change the path from there. Or perhaps I should look at [custom-url-paths](https://github.com/dowjones/gulp-bundle-assets/tree/master/examples/custom-url-paths) example? I wonder if this is possible and if so, how to get started?

@chmontgomery - If you're interested in something like this, here is some code for you from my [staticbuild](https://github.com/devoptix/staticbuild) project:

- [StaticBuild constructor](https://github.com/devoptix/staticbuild/blob/6a650ecbf83660106080eded52a09833e0d24479/index.js#L80) - *An all lowercase alphabet is used here. The default salt will never change. Both can be configured by the end-developer.*
```js
  this.hashids = {
    alphabet: '0123456789abcdefghijklmnopqrstuvwxyz',
    minLength: 4,
    salt: 'BpoIsQlrssEz56uUbfgLu5KNBkoCJiyY'
  };
  this.versionHashIds = {}; // cache of results.
```

- [versionToHashId and versionToInt](https://github.com/devoptix/staticbuild/blob/6a650ecbf83660106080eded52a09833e0d24479/index.js#L154) - *the `hashids.current` object is configured with the alphabet and other options [here](https://github.com/devoptix/staticbuild/blob/6a650ecbf83660106080eded52a09833e0d24479/index.js#L280)*.
```js
StaticBuild.prototype.versionToHashId = 
function (version) {
  var vh = this.versionHashIds[version];
  if (vh)
    return vh;
  var vi = StaticBuild.versionToInt(version);
  vh = this.hashids.current.encode(vi);
  this.versionHashIds[version] = vh;
  return vh;
};

function versionToInt(version) {
  version = String.prototype.trim.call(version);
  var parts = String.prototype.split.call(version, '.');
  var i, len = parts.length;
  for (i = 0; i < len; i++)
    parts[i] = lodash.padLeft(parts[i], 3, '0');
  version = parts.join('');
  return parseInt(version, 10);
}
StaticBuild.versionToInt = versionToInt;
StaticBuild.prototype.versionToInt = versionToInt;
```

**Comment by waynebloss** [comment]
You know what, I was looking at [gulp-rev](https://github.com/sindresorhus/gulp-rev) and [rev-hash](https://github.com/sindresorhus/rev-hash) today and I changed my mind thanks to the article linked to in the rev-hash readme - it's the best way to go for bundling.

I'm going to just use my version hashing procedures to make version directories for my app's static html (e.g. `/urlpath/to/myapp/x8uvi0/`)  and use [gulp-bundle-assets](https://github.com/dowjones/gulp-bundle-assets) or just gulp for bundling styles and scripts. I think I can figure out the rest. Thanks for your work!

**Comment by chmontgomery** [comment]
sounds like you got it.

A couple observations:

1. gulp-rev is predicable in the sense that the hash is generated based on the file contents. The hash will always be the same as long as the file contents don't change.
2. you can use `gulp-bundle-assets` and a custom hash algorithm together. [Take this example](https://github.com/dowjones/gulp-bundle-assets/blob/master/examples/custom-url-paths/bundle.config.js#L3), which allows you to set a custom name and path to your bundle. Since the `bundle.config.js` is just javascript, you can simply require whatever custom hashing algorithm you want and use it as the bundle name/path.

Hope that helps!
