### ISSUE TITLE
Custom targets for bundled scripts and styles?

### ISSUE THREAD

**Issue by alexweissman** [dowjones/gulp-bundle-assets#76]
Thanks for the great plugin!  This seems like the exact solution I need for a full-fledged asset manager.

This issue relates to #22 and #60.  In addition to specifying custom bundle directories in the `bundle.result.json`, it would also be useful if I could specify custom target directories for different types of assets.  For example, multiple bundles' Javascript assets could be written to `public/js/`, while CSS assets could all be written to `public/css/`.

Is this currently possible?

**Comment by Waymoot** [comment]
I second this suggestion.
I had to run two different bundle configs separating CSS and JS just to make this happen.

**Comment by chmontgomery** [comment]
actually this is possible, however poorly documented. You can accomplish this by adding the paths as part of the bundle name in `bundle.config.js` as seen here: https://github.com/dowjones/gulp-bundle-assets/blob/master/examples/custom-url-paths/bundle.config.js

For your use case, it would basically look like this:

```
// bundle.config.js
module.exports = {
  bundle: {
    'js/main': {
      scripts: './content/*.js'
    },
    'css/main': {
      styles: './content/*.css'
    }
  }
};
```

```
// gulpfile.js
gulp.task('bundle', function () {
  return gulp.src('./bundle.config.js')
    .pipe(bundle())
    .pipe(gulp.dest('./public'));
});
```

So the resulting files would be `public/js/main.js` and `public/css/main.css`

Please let me know if that answers your question

**Comment by Waymoot** [comment]
Wow that looks to solve the issue :+1: 
I have to check it out and yes, this really should be documented better because that was a great feature.

**Comment by alexweissman** [comment]
Awesome, thanks for the quick reply!  I'll try this out.

**Comment by alexweissman** [comment]
It looks like my question is actually a duplicate of #49.  Should we add it to the Wiki?

**Comment by chmontgomery** [comment]
@alexweissman definitely. want to take a crack at writing up some markdown for documenting this?

**Comment by alexweissman** [comment]
[Done](https://github.com/dowjones/gulp-bundle-assets/wiki).

**Comment by chmontgomery** [comment]
@alexweissman perfect! thanks!
