### ISSUE TITLE
Use a JSON object, rather than `bundle.config.js`, as the source configuration?

### ISSUE THREAD

**Issue by alexweissman** [dowjones/gulp-bundle-assets#78]
I'm still pretty new to Node and Gulp, and I've been playing with streams and vinyl to try to get this to work, but I can't seem to figure it out.

Basically, I'd like to use a pure JSON file as my input stream, rather than `bundle.config.js`, which requires the extra `module.exports = ` at the beginning.  It seems that I can use `require` to load my JSON file, `bundle.config.json`, into `bundle.config.js`:

```
// bundle.config.js
module.exports = require('./bundle.config.json');
```

But, is there a way to avoid the need for `bundle.config.js` altogether, and load `bundle.config.json` directly in my gulpfile?

**Comment by chmontgomery** [comment]
have you already tried just piping the json file directly? e.g. 

```
gulp.task('bundle', function() {
  return gulp.src('./bundle.config.json')
    .pipe(bundle())
    .pipe(gulp.dest('./public'));
});
```

**Comment by alexweissman** [comment]
Derp.  That works!

So, what's the point of `module.exports = `, then?

**Comment by chmontgomery** [comment]
@alexweissman it's a node-ism. `module.exports` is needed for `.js` files, but you can also simply `require` a json file directly.

**Comment by chmontgomery** [comment]
@alexweissman again, this isn't documented either. Perhaps another wiki entry? ;)

**Comment by alexweissman** [comment]
Done!
