### ISSUE TITLE
Result filename GUID causing trouble

### ISSUE THREAD

**Issue by amcpanaligan** [dowjones/gulp-bundle-assets#81]
Hi, 

I'm wondering if I can turn off or override the guid like characters when gulp-bundle-assets is executed.
"vendor-cbf4577cc3.js" how can I explicitly define a filename for this removing the auto generated "cbf4577cc3" or just replacing it with my preferred string as a whole. Docs are complicated. I don't want to use result.json, I have tfs, I would not want to check in all different files when I'm bundling new assets

**Comment by chmontgomery** [comment]
@amcpanaligan the guid in the file name is controlled by the `rev` key in your `bundle.config.js`. To disable it, simply use `false`, e.g.:

```
module.exports = {
  bundle: {
    main: {
      scripts: [
        {src: './bower_components/jquery/dist/jquery.js', minSrc: './bower_components/jquery/dist/jquery.min.js'},
        {src: './bower_components/angular/angular.js', minSrc: './bower_components/angular/angular.min.js'}
      ]
      options: {
        rev: false
      }
    }
  }
};
```

See here for an example: https://github.com/dowjones/gulp-bundle-assets/blob/master/examples/per-environment/bundle.config.js#L14

Also, if you think the docs are complicated, a community wiki has been started for general FAQ that you're welcome to help with: https://github.com/dowjones/gulp-bundle-assets/wiki

**Comment by chmontgomery** [comment]
If this doesn't answer your question, let me know and we can reopen this issue.
