### ISSUE TITLE
Defining output paths for JS / CSS files

### ISSUE THREAD

**Issue by inertum** [dowjones/gulp-bundle-assets#93]
Is there a way to give CSS/JSS different output paths

/assets/js <--- js files
/assets/css <-- css files
/assets/img <-- image files

so that the results json also reflects these?

**Comment by chmontgomery** [comment]
yep.

see this issue for details: https://github.com/dowjones/gulp-bundle-assets/issues/76

Also someone wrote up a wiki post as well: https://github.com/dowjones/gulp-bundle-assets/wiki/How-do-I-specify-separate-target-subdirectories-for-bundled-scripts-and-styles%3F

**Comment by inertum** [comment]
Thank, sorry for the duplicate
