### ISSUE TITLE
Disable bundling for dev environment

### ISSUE THREAD

**Issue by AndrewCraswell** [dowjones/gulp-bundle-assets#94]
There ought to be some mechanism to produce the bundle.result.json file without actually bundling any of the files. My team would like to have a **dev** build process where files aren't bundled, and a **production** process that bundles them all. We had thought about creating a different gulp task for each environment. The **dev** task wouldn't utilize gulp-build-assets. However, our HTML is reading in the files from the bundle.result.json mapping, and I'm not sure how to toggle that based on the environment.

Seems you can toggle every feature (minify, uglify, etc) but can't disable bundling. This could be a useful enhancement.

**Comment by AndrewCraswell** [comment]
Didn't realize this is a duplicate of #90.

**Comment by PlasmaPower** [comment]
I think this is somewhat different than #90. In that issue, the author wants to simply output paths to the unbundled files. In this issue, the files would still be processed, but they would not be bundled. Do you need to process the files, or is a relative path to the source good?

**Comment by PlasmaPower** [comment]
In addition, even if the bundle results are changed to reference the source, the files would still be processed and bundled (even though they aren't used). I'm thinking you basically want a passthrough option, that still generates the "bundle" results. Maybe a separate module would be more appropriate?
