### ISSUE TITLE
Possible to add async/defer to result script tags?

### ISSUE THREAD

**Issue by AndrewCraswell** [dowjones/gulp-bundle-assets#97]
I searched through the documentation but didn't see any mention of how to configure certain bundles to add async or defer attributes to the script elements. Is this already possible, or is this a feature request you'd consider approving a PR for?

**Comment by chmontgomery** [comment]
Yes, this is definitely possible. Unfortunately the documentation is a
little hidden. See examples/custom-result
https://github.com/dowjones/gulp-bundle-assets/tree/master/examples/custom-result#custom-results

I would accept PRs to update the docs to make this more discoverable. A
wiki page would also do the trick.

Thanks. Chris

**Comment by chmontgomery** [comment]
if you have more questions let me know
