### ISSUE TITLE
Optional sorting when outputUnprocessed: true

### ISSUE THREAD

**Issue by nathanwoulfe** [dowjones/gulp-bundle-assets#98]
Currently using the outputUnprocessed flag for dev environments, which is awesome. Only issue is some bundles require loading files in a particular order - is it possible to add an option (something like sortUnprocessed), to optionally disable the alpha-order sorting?

**Comment by chmontgomery** [comment]
have you tried the `order` option? https://github.com/dowjones/gulp-bundle-assets/tree/master/examples/guarantee-content-order

Does that fit your use-case?

**Comment by nathanwoulfe** [comment]
Not sure that this is the same issue - when we build the bundles, they are output with the files in the same order as defined in bundle.bundleName.scripts[].

The issue is when using the outputUnprocessed flag to generate the bundle-files.json file, which contains the raw file references:

```
  "my-bundle": {
    "styles": [
      "<link href='/styles/styles.css' media='all' rel='stylesheet' type='text/css'/>"
    ],
    "scripts": [
      "<script src='/scripts/somejs.js' type='text/javascript'></script>",
      "<script src='/scripts/this-should-be-first.js' type='text/javascript'></script>"
    ]
  },
```

I need to control the output order in this file, not the actual bundle. Is that possible with `order`? I didn't have any luck getting it to work.

**Comment by chmontgomery** [comment]
Now I see what you're saying. No, there is nothing built in to make that possible currently. I take PRs!

**Comment by nathanwoulfe** [comment]
Rightio, I'll have a crack...

**Comment by nathanwoulfe** [comment]
Any plans for a 2.29 release? Would love to use this in production, but need the npm package

**Comment by chmontgomery** [comment]
done! let me know if you see any issues

**Comment by nathanwoulfe** [comment]
Champion, works as expected.
